- name: Set timezone to Asia/Tokyo
  timezone:
    name: Asia/Tokyo

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - update_package

- name: install neccesary packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - vim
    - git
    - dnsutils
    - iotop
    - htop
    - tcpdump
    - telnet
    - ngrep
    - iperf3
    - linux-perf
    - strace
    - iptables-persistent
    - smartmontools
    - traceroute
    - lsof
    - bash-completion
    - jq
    - moreutils
    - tmux
    - rsyslog

- name: install packages to use repository over https
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common

- block:
    # see: https://www.speedtest.net/ja/apps/cli
    - name: check speedtest repository
      stat:
        path: /etc/apt/sources.list.d/ookla_speedtest-cli.list
      register: repo

    - name: get speedtest gpg key and repository
      shell: curl -s https://packagecloud.io/install/repositories/ookla/speedtest-cli/script.deb.sh | sudo bash
      when: not repo.stat.exists
      ignore_errors: "{{ ansible_check_mode }}"

    - name: install speedtest
      apt:
        name: speedtest
        state: present
        update_cache: yes
      ignore_errors: "{{ ansible_check_mode }}"
  when: '"kubernetes_master" in group_names'

- name: setup git config
  git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: global
  loop:
    - { name: 'user.name', value: 'pi'}
    - { name: 'user.email', value: 'pi@example.com'}
    - { name: 'core.editor', value: 'vim'}
  become: False
  ignore_errors: "{{ ansible_check_mode }}"
