# ファイルとしては一応eth0〜eth2まで用意している
- name: "copy {{ local_interface }} interface config"
  copy:
    src: "etc/network/interfaces.d/{{ local_interface }}"
    dest: "/etc/network/interfaces.d/{{ local_interface }}"
    owner: root
    group: root
    mode: '0644'

- name: install dhcp-server package
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - isc-dhcp-server

- name: start and enable dhcpcd
  systemd:
    name: dhcpcd
    state: started
    enabled: yes

- name: copy dhcpd config
  copy:
    src: etc/dhcp/dhcpd.conf
    dest: /etc/dhcp/dhcpd.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart dhcpcd
