- name: setup first network settings
  block:
    - include_tasks: dhcp_server.yml
    - include_tasks: routing.yml
  when: ('localhost' in group_names)

- name: setup other network settings
  include_tasks: others.yml
  when: ('localhost' not in group_names)
