- name: enable ip forwarding
  sysctl:
    name: net.ipv4.ip_forward
    state: present
    value: '1'

- name: setup forward table in iptables
  block:
    - name: add masquerade setting
      iptables:
        table: nat
        chain: POSTROUTING
        out_interface: "{{ global_interface }}"
        jump: MASQUERADE
      notify:
        - preserve iptables settings

    - name: add inbound forward setting
      iptables:
        chain: FORWARD
        in_interface: "{{ global_interface }}"
        out_interface: "{{ local_interface }}"
        ctstate: RELATED,ESTABLISHED
        jump: ACCEPT
      notify:
        - preserve iptables settings

    - name: add outbound forward setting
      iptables:
        chain: FORWARD
        in_interface: "{{ local_interface }}"
        out_interface: "{{ global_interface }}"
        jump: ACCEPT
      notify:
        - preserve iptables settings
