- name: restart dhcpcd
  systemd:
    name: dhcpcd
    state: restarted

- name: restart isc-dhcp-server
  systemd:
    name: isc-dhcp-server
    state: restarted

- name: preserve iptables settings
  command: netfilter-persistent save
