- name: swap off
  systemd:
    name: dphys-swapfile
    state: stopped
    enabled: no

# see: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
- name: install pakages needed to use the kubernetes repository
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gpg

- name: create keyrings directory
  file:
    path: /etc/apt/keyrings
    owner: root
    group: root
    state: directory
    mode: '0755'

- name: add kubernetes's official GPG key
  shell: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  when: not keyring.stat.exists
  ignore_errors: "{{ ansible_check_mode }}"

- name: create kubernetes repository file
  apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /
    filename: kubernetes
    state: present

- name: install kubernetes
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - kubelet
    - kubeadm
    - kubectl
  ignore_errors: "{{ ansible_check_mode }}"

- name: add kubectl completion
  copy:
    src: etc/bash_completion.d/kubectl
    dest: /etc/bash_completion.d/kubectl
    owner: root
    group: root
    mode: '0644'
